# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine

# Set working directory
WORKDIR /app

# Copy the project files
COPY . .

# Install the project
RUN pip install --no-cache-dir .

# Start the MCP server
CMD ["python", "-m", "lilith_shell.executor"]
